version: "3"
services:
  backend-prod:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production

    command: ["node", "app.js"]

  react-client-prod:
    restart: always
    build:
      context: ./frontend
    ports:
      - "80:80"
#

# docker-compose -f docker-compose-prod.yml up --build
# docker-compose -f docker-compose-prod.yml down && docker-compose -f docker-compose-prod.yml up --build
