version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5501:5501"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - NODE_ENV=development

    command: ["nodemon", "-L", "app.js"]

  react-client:
    stdin_open: true
    restart: always
    ports:
      - "81:3001"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start"]
#

# docker-compose up
# docker-compose down && docker-compose up --build
